- readme.md
> fixed Glitch link

- src/components/networked-share.js
- src/components/networked.js
per Slack discussion, 
sync tests still fail due to separate bug
> fix template handling in networked and networked-share

- server/static/disconnect.html
- src/NetworkConnection.js
- src/NetworkEntities.js
- src/adapters/EasyRtcAdapter.js
- src/adapters/NoOpNetworkAdapter.js
- src/adapters/WsEasyRtcAdapter.js
- src/components/networked-scene.js
- src/components/networked.js
> Disconnect support

- server/static/basic.html
- src/adapters/EasyRtcAdapter.js
- src/adapters/WsEasyRtcAdapter.js
Was causing the HEAD timeOffset request to fire as fast as possible.
> Fix serverTimeRequests bug

- README.md
> Fix typo defualt => default

- README.md
- src/Schemas.js
- tests/unit/Schemas.test.js
- tests/unit/helpers.js
- tests/unit/karma.conf.js
Checks that the template is actually a <template> and only has one root child.
> Template validation

- docs/RELEASE_NOTES.md
The release notes are using the out of date API. Oops.
> attachLocalTemplate -> attachTemplateToLocal in release notes

- examples/basic-audio.html
... one word can make a huge difference. :)
Took me some time to find this, though.
> added ' networked-audio-source'

- docs/getting-started-local.md
- examples/basic-audio.html
- examples/basic-events.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/google-blocks.html
- examples/ownership-transfer.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
I also added docs for serving the local server over HTTPS using [ngrok](https://ngrok.com/).
> Fix HTTP resource warning in examples

- src/adapters/naf-socketio-adapter.js
**PR Changes:**
Used Method: `NAF.connection.disconnect()`
Error: `TypeError: this.adapter.disconnect is not a function`
Fixed error #215 
closes #215
> Fixed socket adaptor error when disconnect method called

- .gitignore
- src/NetworkConnection.js
- src/NetworkEntities.js
- src/components/networked.js
- src/utils.js
- tests/unit/networked.test.js
Retrieve all recent changes from the mozilla's fork https://github.com/MozillaReality/networked-aframe
closes #241
> Merge mozilla changes

- README.md
- docs/RELEASE_NOTES.md
- examples/index.html
In preparation to the 0.8.0 release #253 document what changed. Add some changes described in #246
> Release notes for 0.8.0

- README.md
- src/components/networked.js
> update doc about removing entities when creator disconnect

- examples/basic-audio.html
- examples/basic-events.html
- examples/basic-video.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/ownership-transfer.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
> Fix snow particles with aframe 1.2.0

- .github/workflows/ci.yml
If someone has an idea why Github Actions fails on some tests....
Let's try to disable firefox and see if chrome is ok...
https://github.com/networked-aframe/networked-aframe/runs/3171559047?check_suite_focus=true
```
FAILED TESTS:
NetworkEntities
✖ "before each" hook for "removing many entities"
Firefox 90.0.0 (Ubuntu 0.0.0)
Timeout of 3000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
module.exports.whenEntityLoaded/<@webpack:///./src/utils.js?:6:5
[129]</module.exports<.prototype<.emit.value</<@webpack:///./node_modules/aframe/dist/aframe-master.js?:67458:16
emitLoaded@webpack:///./node_modules/aframe/dist/aframe-master.js?:67323:16
```
https://github.com/networked-aframe/networked-aframe/runs/3171527673?check_suite_focus=t …
> Fix flaky tests

- examples/basic-audio.html
- examples/basic-multi-streams.html
- examples/basic-video.html
- examples/css/style.css
> reusable button style and allow several buttons on the same line

- README.md
Details on https://github.com/networked-aframe/naf-janus-adapter/pull/23
> Link to the janus-plugin-sfu fork in networked-aframe organization

- examples/basic-persistent.html
- examples/index.html
- examples/js/color-changer.component.js
This closes #238
Dynamically spawned persistent spheres is another use case entirely. I'll work on an advanced example.
> Add a persistent sphere example

- README.md
- src/utils.js
This is another undocumented feature.
Is my explanation clear enough? I may go too much in the details? ah ha
> documentation about networked schema requiresNetworkUpdate

- .husky/pre-commit
- package-lock.json
- package.json
Add pre-commit hook with husky to run eslint against js files and prettier on html files.
> add pre-commit hook to enforce style for new contributions

- examples/js/spawn-in-circle.component.js
I also updated https://glitch.com/edit/#!/naf-project
> use degToRad from THREE.MathUtils to be compatible with aframe master

- .github/workflows/ci.yml
similar to https://github.com/aframevr/aframe/pull/5104
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
> allow only the contents read permission in CI

- examples/basic.html
- examples/nametag.html
- examples/tracked-controllers.html
Use a version of movement-controls allowing your to move with left joystick, and moving camera with right joystick.
> use better movement-controls version in examples

- examples/basic-audio.html
- examples/basic-events.html
- examples/basic-multi-streams.html
- examples/basic-persistent.html
- examples/basic-video.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/nametag.html
- examples/ownership-transfer.html
- examples/persistent-peer-to-peer.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
Update aframe-environment-component to 1.3.2 to be compatible with aframe 1.4.0
See https://github.com/supermedium/aframe-environment-component/pull/78
> Update aframe-environment-component to 1.3.2

- README.md
> Offline usage

- docs/hosting-networked-aframe-on-a-server.md
Glitches FAQ moved and Heroku no longer has a free tier.
> Update links hosting-networked-aframe-on-a-server.md

- README.md
Add link to https://github.com/networked-aframe/naf-nametag-solidjs
> Add link to example Nametags with UI in SolidJS/Tailwind CSS

- README.md
I wrote an example of using the 40 VALID (Validated Avatar Library for Inclusion and Diversity) avatars (5 outfits each) with networked-aframe.
demo: https://naf-valid-avatars.glitch.me/
github: https://github.com/networked-aframe/naf-valid-avatars
> Add new example "Realistic animated avatars with UI to choose your avatar"

- examples/adapter-test/adapter-test-receive.html
- examples/adapter-test/adapter-test-send.html
- examples/basic-audio.html
- examples/basic-chat.html
- examples/basic-events.html
- examples/basic-multi-streams.html
- examples/basic-persistent.html
- examples/basic-video.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/nametag.html
- examples/ownership-transfer.html
- examples/persistent-peer-to-peer.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
Update examples to aframe 1.5.0, environment 1.3.3 and aframe-extras 7.2.0.
> Update examples to aframe 1.5.0

- .github/workflows/ci.yml
> Update GitHub CI

- src/adapters/naf-socketio-adapter.js
- src/adapters/naf-webrtc-adapter.js
> Properly implement reconnect for socketio and webrtc adapters
