- server/static/child-entities.html
- src/NafIndex.js
- src/NetworkConnection.js
- src/NetworkEntities.js
- src/components/networked.js
- tests/unit/NetworkEntities.test.js
WIP Fixes #41 by:
1. On opening a datachannel only send a sync packets to the user for which the channel was opened. Previously when a new user joins a room with N people in it, the new user would broadcast a sync packet for each of their entities N times. If those entities had children, there is a chance the parent component might get added to the child queue multiple times, and then get instantiated multiple times. This prevents that by only sending a single sync packet to each client.
2. If an entity is still attempted to be instantiated multiple times, don't, and log a warning.
> Fix multiple entity instantiation

- src/adapters/FirebaseWebRtcAdapter.js
- src/utils.js
The Firebase adapter was not using the specified app name (which becomes appId).  Instead, the default app name was always used, which could cause conflicts if actually trying to use more than one app per Firebase endpoint.
On the assumption that said behavior was unintentional, these changes correct that behavior.
(Note: the sanitization of the selector portion of the Firebase key was necessary in prior versions, but may have been replaced by different mechanisms in the latest, so not sure if that portion is still required.)
> Fix firebase app

- docs/getting-started-local.md
Following along with the getting started tutorial npm threw: `Error: Cannot find module '/home/miles/repos/naf-tutorial/server/server.js` when I tried to `npm start`. I think you meant to use the `easyrtc-server.js`?
> There is no file called 'server.js' in ./server

- src/components/networked.js
Wait for templates to be rendered before calling syncAll/networkUpdate. This was causing issues when network schemas defined child selectors for their template elements. Before this fix the query selectors for determining what component data to sync were executed before the template was rendered.
> Wait for template before syncAll/networkUpdate

- src/components/networked.js
- tests/unit/networked.test.js
Changing component data directly is bad practice as it leads to internal inconsistencies in a-frame. 
For example, the network id may get clobbered if a-frame calls `updateComponents` after an asset timeout.
> Use setAttribute to change component data

- src/components/networked.js
`setAttribute` replaces the `this.data` object entirely, so we can't reference the old one.
> Avoid caching data

- src/components/networked-audio-source.js
Added required attributes to the audio div, as shown in: https://github.com/priologic/easyrtc/pull/355
> fix audio playback on IOS safari

- server/easyrtc-server.js
I recently upgraded node to v9.3.0 and started receiving this error: 
```
Error [ERR_SERVER_ALREADY_LISTEN]: Listen method has been called more than once without closing.
at Server.listen (net.js:1458:11)
at Object.<anonymous> (/Users/rlong/workspace/networked-aframe/server/easyrtc-server.js:78:11)
at Module._compile (module.js:660:30)
at Object.Module._extensions..js (module.js:671:10)
at Module.load (module.js:573:32)
at tryModuleLoad (module.js:513:12)
at Function.Module._load (module.js:505:3)
at Function.Module.runMain (module.js:701:10)
at startup (bootstrap_node.js:194:16)
at bootstrap_node.js:618:3
```
I removed the duplicate call to `.listen()` and it seems to have fixed this issue.
> Fix error in easyrtc server when calling listen twice.

- src/components/networked-audio-source.js
This helps solve two issues with Safari:
1. If you want to use the audio stream in Safari, e.g to visualize the audio, you need access to the MediaStreamSource that networked-aframe creates, since Safari will play garbled audio if you try to `createMediaStreamSource` twice on the same stream. This PR adds an `sound-source-set` event that passes the sound source to any consumers.
2. Safari on iOS would play audio from the hidden `Audio` node that we were creating as a workaround for Chrome. This change applies the workaround to chrome browsers only.
> Emit sound source and fix audio output for safari

- src/NetworkConnection.js
- src/components/networked-scene.js
Ideally this should be a promise that resolves when connect has completed, but this could be formalized later.
> Allow adapters to return a value from connect()

- package.json
networked-aframe currently exposes the bundled/dist version of networked-aframe in package.json. Including the bundled version in a webpack project makes it so the source map generated points to the sourcemap of the bundle and not the individual files of the library. The downsides of doing this is that all consumers of the library need to have ES2015 support. I think it's safe now to require ES2015 as most developers are using Babel if they are requiring the npm package.
> Change package.json to expose index.js

- package.json
- src/ComponentHelper.js
- src/components/networked.js
- src/index.js
- src/utils.js
- tests/unit/networked_remote.test.js
This is different take on https://github.com/networked-aframe/networked-aframe/pull/124 
It uses a new package I wrote: https://github.com/InfiniteLee/buffered-interpolation
It has 3 advantages:
1. It uses a (configurable) buffer that provides some network jitter protection and also makes sure that updates received continuously are not lost (e.g. lerping from A -> B -> C will no longer "skip" B if C is received before B is reached).
2. It reuses the last received network update if no updates are sent. This prevents the issue where the lerp duration is determined by how long ago the last update was received.
3. It has functionality to use hermite interpolation, if we decide to enable syncing of a velocity component. This should work very well for physics enabled objects, ballistic …
> buffered interpolation

- README.md
The event type that is fired is `'entityRemoved'`
https://github.com/networked-aframe/networked-aframe/blob/4c270ff0dc5b6429293c110141697fa326fdef0b/src/components/networked.js#L441
> Correct networked entity deletion event name

- src/components/networked.js
This PR changes the contract for requiresNetworkUpdate custom predicate on the schema to now be a second order function, like the default, so it can create component instance-level bindings for state (like as is done in the default for the previous value.)
> Assume requiresNetworkUpdate is a second order function

- src/NetworkEntities.js
- src/components/networked.js
Sometimes you don't want an entity to be destroyed when its owner disconnects. This could be a model or drawing added to a scene by a user or a singleton object like a presentation controller.
This approach adds the `persistent` property to the `networked` component, and, on remote owner disconnect, attempts to take ownership of persistent entities rather than delete them. It's not the most efficient approach, as, in a room with multiple users, everyone races for ownership and the slowest wins. It is, however, achieved with minimal changes and should work even if the original owner crashes or otherwise disconnects unexpectedly.
If you're interested in this approach, I can add documentation and testing to this PR. If you're not, no sweat, just wanted to share what we're using.
> A simple take on networked entity persistence

- src/adapters/naf-socketio-adapter.js
- src/adapters/naf-webrtc-adapter.js
On Chrome and Firefox, `new Date() + this.avgTimeOffset` results in a date string with `avgTimeOffset` appended as a string to the end.
This pull request converts the date to a number, which ensures that addition happens numerically, ensuring that `getServerTime` returns a time number, as expected (as evidenced by comparing `getServerTime()` using less than and greater than elsewhere in the code)
> Fix getServerTime returning a string

- src/components/networked.js
Sometimes the `this.data` value is undefined if there is a high load of messages coming in, such as when a VR headset joins. This causes the other avatar to disappear from the screen, even though it still appears in the occupants array and the other player can still see this one.
Discussion in issue #200
> components/networked.js: this.data can be undefined

- src/adapters/naf-webrtc-adapter.js
Fixes the 1-way audio issue:
TL;DR: only one user can talk with the native webrtc adapter. This PR should fix this bug.
Closes https://github.com/networked-aframe/networked-aframe/issues/194
Adding this snippet seems to do the trick:
```javascript
localStream.getTracks().forEach(
track => {
Object.keys(self.peers).forEach(peerId => { 
self.peers[peerId].pc.addTrack(track, localStream) 
})
})
```
Safari doesn't seem to work (before & after this PR), but the [commented link](https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenViduInternal/WebRtcPeer/WebRtcPeer.ts#L154) in the webrtc adapter file seems useful. I'll try to fix Safari functionality in this PR as well.
Tested by:
- opening two tabs in Chrome for localhost:8080/basic-audio.html.
- served over HTTPS using …
> Fix 1-way audio bug

- README.md
I already removed the `.travis.yml` file in a previous commit.
See #237 to move to Github Actions.
> Remove travis-ci badge

- src/components/networked-audio-source.js
Properly cleanup audio element in `networked-audio-source` remove function like we do for video in `networked-video-source` ([see code](https://github.com/networked-aframe/networked-aframe/blob/2c64d0dc7baff5b3ff9c2e83eb32545f7da34856/src/components/networked-video-source.js#L74-L76)).
This is to be sure that the resource is released.
In Chrome 92, there is now limits on WebMediaPlayers you can create. See
https://bugs.chromium.org/p/chromium/issues/detail?id=1232649
https://chromium-review.googlesource.com/c/chromium/src/+/2816118
I didn't encounter any issue myself, but I guess it doesn't hurt to properly release the audio element that way.
> properly cleanup audio element in networked-audio-source remove

- package.json
Update engines to node>=16 npm>=7 so glitch selects node v16.12.0 npm 7.20.6 environment instead of node 10.
The new package-lock.json lockfile v2 format requires npm >= 7.
> update engines to node>=16 npm>=7

- src/adapters/EasyRtcAdapter.js
> Fix regression introduced in 0.9.0 that failed to remove mediaStreams properly

- README.md
- examples/basic-persistent.html
- examples/index.html
- examples/js/persistent-p2p.component.js
- examples/js/spawner-persistent.component.js
- examples/persistent-peer-to-peer.html
The example is similar to #326 but here with spawned spheres.
I created a `spawner-persistent` component and `persistent-p2p` that handle the logic of keeping the persistent entities peer to peer. The spheres are kept in the room if there is at least one participant remaining in the room.
This is related to #265, it's the first time we use the `applyPersistentFirstSync` api in an example.
Next example would be persisting it server side.
> Add a spawned persistent spheres (peer to peer) example

- src/components/networked.js
Add compatibility with threejs r141 (current aframe master), THREE.Math was removed, you need to use THREE.MathUtils now.
Note that THREE.MathUtils was available since at least threejs r125 aframe 1.2.0.
But a reminder latest networked-aframe is for aframe 1.3.0 and above only because of the buffered-interpolation dependency.
> compatibility with threejs r141

- .prettierrc.json
- examples/360.html
- examples/adapter-test/adapter-test-receive.html
- examples/adapter-test/adapter-test-send.html
- examples/adapter-test/index.html
- examples/ar-index.html
- examples/basic-2.html
- examples/basic-4.html
- examples/basic-ar.html
- examples/basic-audio.html
- examples/basic-events.html
- examples/basic-multi-streams.html
- examples/basic-persistent.html
- examples/basic-video.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/google-blocks.html
- examples/index.html
- examples/ownership-transfer.html
- examples/persistent-peer-to-peer.html
- examples/shooter-2.html
- examples/shooter-ar.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
This closes #325
- added a prettier config with no trailing comma, single quote to match what we had previously but increase to 120 characters per line to have the avatar template entities on single line like we discussed.
- removed the imgur images, plane, sky, lights, particles
- used the arches environment component in all examples
- included the schema hack like I did in the basic.html example
- added a cameraRig to all examples
- removed the github corner on all examples, I left it only on the index.html
- renamed camera-rig to cameraRig, and local-avatar to player in tracked-controllers example so this is the same like the other examples
- added an explicit "adapter: wseasyrtc" in the examples where the adapter wasn't defined
> Simplify examples

- .github/workflows/ci.yml
- docs/release-instructions.md
- package-glitch.json
- package.json
- server/easyrtc-server.js
- server/socketio-server.js
- webpack.config.js
See #347 for context.
I introduced some time ago (in https://github.com/networked-aframe/networked-aframe/commit/017d40cca82b0f7666327e0a14a8f49b3224b2ba and https://github.com/networked-aframe/networked-aframe/commit/a97b5e79dd30785557c2f33d184d3741f8315a14) running `npm run build` as part of `npm start` to be sure to have latest build when using `npm start` instead of `npm run dev`. In retrospect, I think this change was wrong, we shouldn't run a build step on `npm start` (for glitch) so I'm reverting this change.
`npm install` is executing `npm run prepare` that is executing `npm run dist` already. I added the `cp -r dist examples` in the prepare script instead. And I fixed the webpack-dev-server config to use the bundle in-memory and not the one from examples/dist when running `npm …
> Don't build on start but only on install

- docs/getting-started-local.md
- examples/360.html
- examples/adapter-test/adapter-test-receive.html
- examples/adapter-test/adapter-test-send.html
- examples/basic-ar.html
- examples/basic-audio.html
- examples/basic-events.html
- examples/basic-multi-streams.html
- examples/basic-persistent.html
- examples/basic-video.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/google-blocks.html
- examples/ownership-transfer.html
- examples/persistent-peer-to-peer.html
- examples/shooter-ar.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
- package-lock.json
- package.json
See 2.5.0 release notes and security advisory at
https://github.com/socketio/socket.io/releases/tag/2.5.0
A new networked-aframe release is not needed, but you need to double check the socket.io version you use in your own projects. On glitch, open the terminal and execute the following:
```
rm -rf package-lock.json node_modules/*
refresh
```
and wait a few seconds, it will automatically do the `npm install` getting the latest versions. (You can open the Logs tab to see that)
Note that on glitch node_modules is a symlink to a volume. If you do `rm -rf package-lock.json node_modules` (without the star), it won't remove the currently installed packages, and `npm install` will still use the old socket.io version.
and for client side, in index.html, use
```
<script …
```
> update socket.io to 2.5.0 to fix engine.io vulnerability

- examples/css/style.css
The issue was this, aframe inspector is using the button class on the inspector buttons, conflicting with the css rule we have in style.css
To fix the issue I modified the css rule to target the buttons in the actions div.
If you have some examples that is using the style.css and the button class, be sure to put the buttons in a div with class actions. All the examples are using this construct since #302
```html
<div class="actions">                                                       
<button id="camera-btn" type="button" class="button">Hide Camera</button> 
</div>
```
> Fix conflicting button style in aframe inspector

- README.md
- examples/tracked-controllers.html
- src/components/networked-hand-controls.js
The networked-hand-controls component introduced in  #355 and #358 is auto creating the template, networked schema and networked component on the corresponding entity. This was apparently confusing for some users, who mixed the old approach and the new component.
I already committed directly on master moving the new section up without changes https://github.com/networked-aframe/networked-aframe/commit/e81604b20c36218d86530d64554ad50c31ea0dc6 and fixed wrong param custom hand model param https://github.com/networked-aframe/networked-aframe/commit/32651f3bd18738801b079c2f468b9cd5baa263c8
In this PR I added some explanation to better understand the difference between hand-controls with custom templates and the new networked-hand-controls.
But thinking about it, We maybe shouldn't auto create …
> Less confusing doc with the new introduced networked-hand-controls

- server/easyrtc-server.js
This refs #257 and closes #169.
Thanks @dirkk0 for the lines.
> add commented lines to enable https on the node server

- README.md
- src/Schemas.js
- src/components/networked-hand-controls.js
Use better default schema with the requiresNetworkUpdate optimization for position and rotation.
Use the same optimization for the default schema used by networked-hand-controls.
As discussed in https://github.com/networked-aframe/networked-aframe/pull/362#issuecomment-1244785047
> Better default schema with the requiresNetworkUpdate optimization

- package-lock.json
- package.json
Someone reported having an error with the github: prefix for the buffered-interpolation dependency with nodejs 14, so I replaced with the alternate syntax documented in https://docs.npmjs.com/cli/v8/configuring-npm/package-json#github-urls in hope this fixes the issue.
I also updated open-easyrtc dependency.
> Remove github: prefix for buffered-interpolation

- README.md
The example can be confusing leading users to believe that hand tracking is supporting while it is, for now at least, not.
> Clarifying hand models versus hand tracking

- README.md
pointing out that it's described in `server/easyrtc-server.js`
> details on https/certs for offline use

- examples/basic-multi-streams.html
- src/adapters/EasyRtcAdapter.js
- src/components/networked-video-source.js
Changes proposed:
- Rotate screen plane by 180 degrees, the screen share was reversed (see modified example)
- Handle stopping screenshare from browser button (video track ended event) (see the added code in the example)
- In the easyrtc adapter, properly clean up pendingMediaRequests['screen'] promise to be able to get the new media stream when the video track end and a new one is added later.
- In networked-video-source component, listen on remotetrack to detect that the stream closed (may not be the right easyrtc api to use, but that works) to clean the video texture so the plane comes back to the defined color (white), and run again getMediaStream to wait on new remote stream.
> Fix screen share stop and restart (fix #299 #402)

- examples/nametag.html
In the nametag example, fix color-changer button not working when there is another button in the page because the selector was too generic.
> Fix color-changer button not working when there is another button in the page

- src/components/networked-video-source.js
Specify colorSpace srgb for video texture for compatibility with aframe 1.5.0 (fix #444)
Thanks @Turtleted21 for the investigation.
> Specify colorSpace srgb for video texture for compatibility with aframe 1.5.0 (fix #444)

- src/components/networked.js
Can be useful to have it exposed so we can use it instead of adding another version of it in a project.
See my comment https://github.com/msub2/aframe-exokit-avatars/issues/8#issuecomment-1816916724
> Expose InterpolationBuffer on NAF global

- src/components/networked-hand-controls.js
The networked-hand-controls component doesn't work properly with aframe-v1.5.0:
1. Hand color is not updated (example: `networked-hand-controls="hand:left;color:gold;"`).
To make it work replace:
https://github.com/networked-aframe/networked-aframe/blob/0f8452331d1d62fed9a76aaf4ab29961c1cc064e/src/components/networked-hand-controls.js#L219-L220
with:
```
const handColor = this.data.color;
newMesh.traverse(function (object) {
if (!object.isMesh) { return; }
object.material.color = new THREE.Color(handColor);
});
```
2. Hand controller does not work if controllerComponent is not specified (example: `networked-hand-controls="hand:right;handModelStyle:controller;"`).
Remove `'gearvr-controls', 'daydream-controls'` from the `controllerComponents` list: …
> fix networked-hand-controls issues with aframe-v1.5.0

- server/socketio-server.js
Use case: experience with 3000 users, using room instancing by batch of 50 users, no audio, no video, only websocket. We are interested only in avatar movements.
For 50 in a room, you probably want to reduce the update rate to 1 per second instead of 15 by setting `NAF.options.updateRate = 1` ([doc](https://github.com/networked-aframe/networked-aframe?tab=readme-ov-file#options))
If you test it inside the networked-aframe repo, be sure to use `npm run dev-socketio` and setting `networked-scene="adapter:socketio"` in the basic.html or basic-chat.html examples.
Be aware there are pending issues with the socketio adapter:
- #242
- #243
That's a quick implementation I tested only with `maxOccupantsInRoom = 3` instead of 50.
I didn't test the load. Someone has to create a script to test 3000 …
> Implement room instancing in socketio-server.js

- package-lock.json
- package.json
- server/easyrtc-server.js
You can still use the mkcert command, but the `npx webpack serve --server-type https` command is also a quick way to generate one.
> Document how to generate a self-signed certificate for local development

- README.md
- examples/360.html
- examples/basic-ar.html
- examples/basic-audio.html
- examples/basic-chat.html
- examples/basic-events.html
- examples/basic-multi-streams.html
- examples/basic-persistent.html
- examples/basic-video.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/google-blocks.html
- examples/nametag.html
- examples/ownership-transfer.html
- examples/persistent-peer-to-peer.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
- src/Schemas.js
Put back ['position', 'rotation'] without requiresNetworkUpdate for default schema, changes that were done in #367 for the 0.11.0 release were not working.
Also better to define yourself requiresNetworkUpdate to use vectorRequiresUpdate over the default defaultRequiresUpdate because it may have an impact on cpu performance over large number of owned entities (1-2ms with 3000 entities), defaultRequiresUpdate may be better for entities that aren't moving much, vectorRequiresUpdate is best used to reduce the sent messages and so the used bandwidth of moving avatars.
Update all examples to use NAF.utils.vectorRequiresUpdate for position and rotation for avatar-template.
> Put back ['position', 'rotation'] without requiresNetworkUpdate for default schema

- examples/basic-chat.html
- examples/basic.html
- examples/nametag.html
- examples/tracked-controllers.html
- src/adapters/EasyRtcAdapter.js
- src/adapters/WsEasyRtcAdapter.js
- src/components/networked.js
- Avoid allocation of an object and array on system tick for the data.d structure.
- Avoid allocation of an object when an entity has components that have changes or fullsync
- Reuse destination object in broadcastData for (ws)easyrtc adapters
- Update to aframe-extras 7.5.2 that has a fix to not allocate an array and object on each tick in gamepad-controls https://github.com/c-frame/aframe-extras/pull/452
> Avoid allocations in tick

- src/components/networked.js
- src/utils.js
- tests/unit/NetworkEntities.test.js
Fix regression since aframe 1.6.0 when networkUpdate is called when the networked component is not yet initialized by checking this.componentSchemas undefined instead of this.data, this.data is always defined now in aframe 1.6.0, also keep now the latest changes that will be used in firstUpdate, and free firstUpdateData when initialized
This fixes #476
> Fix regression avatars disappear in demos since aframe 1.6.0

- server/.prettierrc.json
- server/socketio-server.js
If you want to test, change in `package.json`
```
"socket.io": "^4.8.1"
```
and run
```
npm install
```
in `examples/basic.html`:
```diff
-    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.5.0/socket.io.slim.js"></script>
-    <script src="/easyrtc/easyrtc.js"></script>
+    
+    <script src="/socket.io/socket.io.js"></script>
<a-scene
networked-scene="
room: basic;
-      debug: true;
-      adapter: wseasyrtc;
+      debug: false;
+      adapter: socketio;
"
```
To run with node:
```
node server/socketio-server.js
```
To run with deno:
```
cp server/socketio-server.js server/socketio-server.cjs
deno -A server/socketio-server.cjs
```
To run with bun
```
bun server/socketio-server.js
```
deno is good alternative for performance it seems …
> Add compatibility with socket.io 4.8.1 in socketio-server.js

- README.md
- server/uws-server.cjs
- src/adapters/AdapterFactory.js
- src/adapters/naf-uws-adapter.js
Add uws adapter, equivalent of the socketio adapter but using WebSocket directly and with the reconnection logic from the janus adapter.
You can easily compare `src/adapters/naf-socketio-adapter.js` and `src/adapters/naf-uws-adapter.js` if you're interested in the implementation.
Add the uws server based on https://github.com/uNetworking/uWebSockets.js
see comments in the `server/uws-server.cjs` if you're interested in running it. This is the exact equivalent of `server/socketio-server.cjs` that includes room instancing.
On Raspberry Pi 400, 70 moving users with socketio were taking 100% of cpu, with uws server only 30%.
https://x.com/vincentfretin/status/1866053292972822729
> Add uws adapter and server

- README.md
- examples/360.html
- examples/adapter-test/adapter-test-receive.html
- examples/adapter-test/adapter-test-send.html
- examples/basic-ar.html
- examples/basic-audio.html
- examples/basic-chat.html
- examples/basic-events.html
- examples/basic-multi-streams.html
- examples/basic-persistent.html
- examples/basic-video.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/google-blocks.html
- examples/nametag.html
- examples/ownership-transfer.html
- examples/persistent-peer-to-peer.html
- examples/shooter-ar.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
- package-lock.json
- package.json
- server/easyrtc-server.js
Use the open-easyrtc socket.io-4 branch https://github.com/open-easyrtc/open-easyrtc/pull/70
To update your project, be sure you use latest socket.io client, replace
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.5.0/socket.io.slim.js"></script>
```
by
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.8.1/socket.io.min.js"></script>
```
in `server/easyrtc-server.js` or `server.js`, replace
```js
const socketServer = socketIo.listen(webServer, {"log level": 1});
```
by
```js
const socketServer = socketIo(webServer, {"log level": 1});
```
in `package.json`:
```json
"open-easyrtc": "open-easyrtc/open-easyrtc#9e2e0002ddc939daa36a5b1f499fa8568f3438af",
"socket.io": "^4.8.1"
```
and get the updated dependencies:
```sh
rm -rf package-lock.json …
```
> Update socket.io to 4.8.1 with open-easyrtc socket.io-4 branch

- README.md
- docs/getting-started-local.md
- examples/360.html
- examples/adapter-test/adapter-test-receive.html
- examples/adapter-test/adapter-test-send.html
- examples/basic-ar.html
- examples/basic-audio.html
- examples/basic-chat.html
- examples/basic-events.html
- examples/basic-multi-streams.html
- examples/basic-persistent.html
- examples/basic-video.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/dynamic-room.html
- examples/google-blocks.html
- examples/nametag.html
- examples/ownership-transfer.html
- examples/persistent-peer-to-peer.html
- examples/shooter-ar.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
Update examples to aframe 1.7.0
and remove `renderer="physicallyCorrectLights: true;"` that is now the default.
> Update examples to aframe 1.7.0

- examples/basic-audio.html
- examples/basic-chat.html
- examples/basic-events.html
- examples/basic-multi-streams.html
- examples/basic-persistent.html
- examples/basic-video.html
- examples/basic.html
- examples/child-entities.html
- examples/disconnect.html
- examples/dynamic-room.html
- examples/nametag.html
- examples/ownership-transfer.html
- examples/persistent-peer-to-peer.html
- examples/shooter.html
- examples/tracked-controllers.html
- examples/webrtc.html
Remove ambient light everywhere that was used to compensate a bug in A-Frame 1.6.0 environment 1.3.7 with physicallyCorrectLights: true, scene looks better without that extra light in A-Frame 1.7.0 environment 1.5.0.
> Remove ambient light everywhere
